#!/usr/bin/env python3
# Copyright (c) 2026 Julian Yap
# SPDX-License-Identifier: MIT
"""
Generic DXF cleanup script.

Originally intended to clean up DXF files generated by Ergogen.

Finds LINE endpoints that are very close together but not exactly
coincident (near-duplicate points), and snaps all points in each
cluster to a single shared coordinate. This fixes "Both points are
equal" / sketch solver errors in FreeCAD when converting Draft
geometry to a Sketch.

Usage:
    python dxf_cleanup.py input.dxf [--tol 0.01]

Output:
    input_cleaned.dxf
"""

import sys
import argparse
from pathlib import Path
from itertools import combinations

import ezdxf


def find_zero_length_lines(msp, tol=1e-4):
    """Find LINE entities whose start and end points coincide."""
    return [e for e in msp if e.dxftype() == "LINE" and e.dxf.start.isclose(e.dxf.end, abs_tol=tol)]


def find_degenerate_arcs(msp, angle_tol=1e-3):
    """
    Find ARC entities whose start and end angles are (nearly) identical.
    These have zero angular span -- start point == end point -- and
    contribute no real geometry to the outline. However, many DXF
    importers (including FreeCAD) treat start_angle == end_angle as
    ambiguous and render a FULL CIRCLE instead of nothing, producing
    stray phantom circles after import/pad. This is typically a
    floating-point artifact from upstream tools (e.g. a corner-fillet
    subtraction that should be exactly 0 deg but lands a hair off).
    """
    degenerate = []
    for e in msp:
        if e.dxftype() != "ARC":
            continue
        sa, ea = e.dxf.start_angle, e.dxf.end_angle
        span = abs(sa - ea) % 360
        if span < angle_tol or abs(span - 360) < angle_tol:
            degenerate.append(e)
    return degenerate


def find_overlapping_line_pairs(msp, tol=1e-4):
    """Find pairs of LINEs that share both endpoints (duplicate/overlapping segments)."""
    lines = [e for e in msp if e.dxftype() == "LINE"]

    def pts_match(a, b):
        return abs(a[0] - b[0]) < tol and abs(a[1] - b[1]) < tol

    duplicates = []
    for l1, l2 in combinations(lines, 2):
        s1, e1 = (l1.dxf.start.x, l1.dxf.start.y), (l1.dxf.end.x, l1.dxf.end.y)
        s2, e2 = (l2.dxf.start.x, l2.dxf.start.y), (l2.dxf.end.x, l2.dxf.end.y)
        same = (pts_match(s1, s2) and pts_match(e1, e2)) or (pts_match(s1, e2) and pts_match(e1, s2))
        if same:
            duplicates.append((l1, l2))
    return duplicates


def snap_near_duplicate_points(msp, tol=0.01, verbose_fixes=True):
    """
    Cluster all LINE endpoints that are within `tol` of each other
    (transitively, via union-find) and snap every point in a cluster
    to the cluster's first point. Returns the number of clusters that
    had more than one distinct coordinate (i.e. number of fixes applied).
    """
    lines = [e for e in msp if e.dxftype() == "LINE"]

    # Collect all endpoint references: (x, y, line_entity, attr_name)
    endpoints = []
    for l in lines:
        endpoints.append([l.dxf.start.x, l.dxf.start.y, l, "start"])
        endpoints.append([l.dxf.end.x, l.dxf.end.y, l, "end"])

    n = len(endpoints)
    parent = list(range(n))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(i, j):
        ri, rj = find(i), find(j)
        if ri != rj:
            parent[ri] = rj

    # Union all endpoint pairs within tolerance of each other
    for i, j in combinations(range(n), 2):
        x1, y1 = endpoints[i][0], endpoints[i][1]
        x2, y2 = endpoints[j][0], endpoints[j][1]
        d = ((x1 - x2) ** 2 + (y1 - y2) ** 2) ** 0.5
        if d < tol:
            union(i, j)

    # Group endpoints by cluster root
    clusters = {}
    for idx in range(n):
        root = find(idx)
        clusters.setdefault(root, []).append(idx)

    fixes = 0
    for root, members in clusters.items():
        if len(members) <= 1:
            continue

        coords = {(round(endpoints[m][0], 9), round(endpoints[m][1], 9)) for m in members}
        if len(coords) <= 1:
            continue  # already identical, nothing to fix

        # Snap target = coordinates of the first member in the cluster
        target_x, target_y = endpoints[members[0]][0], endpoints[members[0]][1]

        if verbose_fixes:
            pts_str = ", ".join(f"({endpoints[m][0]}, {endpoints[m][1]})" for m in members)
            print(f"  Cluster -> snapping to ({target_x}, {target_y}): {pts_str}")

        for m in members:
            _, _, line_entity, attr = endpoints[m]
            pt = getattr(line_entity.dxf, attr)
            setattr(line_entity.dxf, attr, (target_x, target_y, pt.z))

        fixes += 1

    return fixes


def cleanup_dxf(input_path, snap_tol=0.01, dup_tol=1e-4, verbose=True):
    doc = ezdxf.readfile(input_path)
    msp = doc.modelspace()

    # 1. Remove zero-length lines
    zero_len = find_zero_length_lines(msp, tol=dup_tol)
    for e in zero_len:
        msp.delete_entity(e)
    if verbose:
        print(f"Removed {len(zero_len)} zero-length line(s)")

    # 2. Remove fully overlapping/duplicate line pairs
    overlaps = find_overlapping_line_pairs(msp, tol=dup_tol)
    for l1, l2 in overlaps:
        msp.delete_entity(l2)
    if verbose:
        print(f"Removed {len(overlaps)} overlapping/duplicate line(s)")

    # 3. Remove zero-angular-span ARCs (phantom full-circle artifacts)
    degenerate_arcs = find_degenerate_arcs(msp)
    for a in degenerate_arcs:
        if verbose:
            c = a.dxf.center
            print(f"  Removing degenerate arc at center ({c.x}, {c.y}), r={a.dxf.radius} "
                  f"(start={a.dxf.start_angle}, end={a.dxf.end_angle})")
        msp.delete_entity(a)
    if verbose:
        print(f"Removed {len(degenerate_arcs)} degenerate (zero-span) arc(s)")

    # 4. Snap all near-duplicate endpoint clusters
    fixes = snap_near_duplicate_points(msp, tol=snap_tol, verbose_fixes=verbose)
    if verbose:
        print(f"Snapped {fixes} near-duplicate point cluster(s)")

    return doc


def main():
    parser = argparse.ArgumentParser(description="Clean up a DXF file for FreeCAD Draft-to-Sketch conversion.")
    parser.add_argument("input", help="Input DXF file")
    parser.add_argument("--tol", type=float, default=0.01, help="Distance tolerance for near-duplicate points (default: 0.01)")
    parser.add_argument("-o", "--output", help="Output file (default: <input>_cleaned.dxf)")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: file not found: {input_path}")
        sys.exit(1)

    output_path = Path(args.output) if args.output else input_path.with_name(f"{input_path.stem}_cleaned.dxf")

    doc = cleanup_dxf(str(input_path), snap_tol=args.tol)
    doc.saveas(str(output_path))
    print(f"Saved: {output_path}")


if __name__ == "__main__":
    main()
